### PR TITLE
Removes leftover files from tests

### PR DESCRIPTION
**Pull request by hgandhi2411**
Address #52 
Removes 
- [x] files leftover from TestRemoveSimulation
- [x] COLVAR and HILLS files leftover from some test (yet to figure out which test)

### CODE REVIEW

**Comment by mehradans92** [comment]
Test fails. @hgandhi2411 
======================================================================
ERROR: test_remove (__main__.TestRemoveSimulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_peptidesim.py", line 297, in tearDown
    shutil.rmtree('test_remove_restart')
  File "/home/mgholiza/.conda/envs/mypepsim/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/mgholiza/.conda/envs/mypepsim/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'test_remove_restart'

======================================================================
ERROR: test_remove_restart (__main__.TestRemoveSimulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_peptidesim.py", line 296, in tearDown
    shutil.rmtree('test_remove')
  File "/home/mgholiza/.conda/envs/mypepsim/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/mgholiza/.conda/envs/mypepsim/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'test_remove'

----------------------------------------------------------------------
Ran 34 tests in 1031.522s

FAILED (errors=2)

**Comment by mehradans92** [comment]
Test passed yet files are not removed. @hgandhi2411

**Comment by mehradans92** [comment]
Test runs fine but traj.trr doesn't get removed.

**Comment by hgandhi2411** [comment]
@mehradans92 the traj.trr issue is addressed by the commit that @whitead merged on master today.

**Comment by mehradans92** [comment]
Great job then

**Pull request merged**
