### PR TITLE
Issue/24

### PR DESCRIPTION
**Pull request by dilnoza92**
This fixes the add_file bug and converts new python scripts to 3. Now, the plumed text which is modified inside a part_2.py is automatically updated in the local directory.

### CODE REVIEW

**Comment by hgandhi2411** [comment]
@dilnoza92 can you point out what exactly you changed in test_peptide.py?
Also, why do you have test_peptide.py and peptide_test.py, are they different?

**Comment by hgandhi2411** [comment]
This is the error when I run tests.
```
_________________________ TestPeptideSimInitialize.test_include_resolution __________________________

def setUp(self):
        self.p = PeptideSim('pinit_test', ['AA', 'REE'], [
                            3, 1], job_name='testing')
>       self.p.initialize()

tests/peptidesim_test.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
peptidesim/peptidesim.py:513: in initialize
    self._add_ions()
peptidesim/peptidesim.py:1270: in _add_ions
    self.log.debug('ndx_output: {}'.format(ti))
/opt/conda/lib/python3.7/logging/__init__.py:1366: in debug
    self._log(DEBUG, msg, args, **kwargs)
/opt/conda/lib/python3.7/logging/__init__.py:1514: in _log
    self.handle(record)
/opt/conda/lib/python3.7/logging/__init__.py:1524: in handle
    self.callHandlers(record)
/opt/conda/lib/python3.7/logging/__init__.py:1586: in callHandlers
    hdlr.handle(record)
/opt/conda/lib/python3.7/logging/__init__.py:894: in handle
    self.emit(record)
/opt/conda/lib/python3.7/logging/__init__.py:1126: in emit
    self.stream = self._open()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <FileHandler /home/whitelab/scratch/peptidesim/package/psim_test/simulation.log (DEBUG)>

    def _open(self):
        """
        Open the current base file with the (original) mode and encoding.
        Return the resulting stream.
        """
>       return open(self.baseFilename, self.mode, encoding=self.encoding)
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/whitelab/scratch/peptidesim/package/psim_test/simulation.log'

/opt/conda/lib/python3.7/logging/__init__.py:1116: FileNotFoundError
```

**Comment by whitead** [comment]
@dilnoza92 This PR changes hundreds of lines for what should be a small change. I understand it's because you ran autopep8 over peptidesim.py but this will make it hard to track changes to the file because it appears as though you rewrote it. Could you please only use autopep8 on the code you wrote. That is what is checked by the bot, that code you write follows pep8 standards.

**Comment by whitead** [comment]
@hgandhi2411 can you confirm that passes on master?

**Pull request closed without merging**
