### PR TITLE
Added instructions on using any new forcefield

### PR DESCRIPTION
**Pull request by hgandhi2411**
Addresses #90 

- [x] Add water selection
- [x] Add instructions on using new FF in input files and Readme.md

### CODE REVIEW

**Comment by hgandhi2411** [comment]
The easiest way to use a new ff is to use `ps.add_file()` and add it to `peptide_structures` dir with `ps._put_in_dir()`. Added instructions for that in input files.
To use a new water model, source code needs to change slightly.

**Comment by whitead** [comment]
Is this ready to be reviewed @hgandhi2411 ?

**Comment by hgandhi2411** [comment]
@whitead This PR is ready to review. Thanks!

**Review by whitead — APPROVED** [review]
Looks good to me!

**Pull request merged**
